---
title: "First Class"
author: "D. Howell"
date: "8/14/2020"
output: 
  html_document:
    theme: flatly
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Welcome!

Zoom Link:  https://oru.zoom.us/j/96881078433

* Personal Introductions
  + Student Introductions
    + Name, Major, Year, Origin
  + Instructor Introduction
    + Educational Background
      + B.S. in Mechanical Engineering from ORU
      + M.S. in Applied Data Science from Syracuse University
    + Professional Background
      + Clinical DB Programmer
      + Data Mining Specialist 
      + Quantitative Research Analyst
* Course Intro
  + Extracting value from data
    + [Statistics](https://towardsdatascience.com/the-5-basic-statistics-concepts-data-scientists-need-to-know-2c96740377ae)
      + Predictive modelling 
      + Analysis of data sets
    + [Computer Science](https://www.dataquest.io/blog/what-is-a-data-engineer/) 
      + Data storage
      + ETL pipelines 
      + Implementing algorithms
      + Automation
  + Applications
    + [Recommendation engines for retail](https://medium.com/humansforai/recommendation-engines-e431b6b6b446)
    + [Fraud detection in banking](https://emerj.com/ai-sector-overviews/artificial-intelligence-fraud-banking/)
    + [Algorithmic trading in private equity](https://www.motherjones.com/politics/2013/02/high-frequency-trading-danger-risk-wall-street/)
    + [Image recognition in healthcare](https://medium.com/activewizards-machine-learning-company/top-7-data-science-use-cases-in-healthcare-cddfa82fd9e3)
    + [Targeted advertising](https://medium.com/@araoyeoluwasegunvhictor/the-application-of-data-science-in-targeted-advertising-e81c1f7f5b62)
    + [Natural language processing in human/computer interaction](https://towardsdatascience.com/how-amazon-alexa-works-your-guide-to-natural-language-processing-ai-7506004709d3)
    + [Professional sports management optimization](https://towardsdatascience.com/scope-of-analytics-in-sports-world-37ed09c39860)
  + [Data Science as a Career](https://www.computerscience.org/careers/data-science/)
  + How is the course structured?
    + Changes from last semester
    + Review units and topics on [schedule](https://d2l.oru.edu/d2l/le/content/828830/viewContent/3628003/View)
* Course Administration
  + Review [syllabus](https://d2l.oru.edu/d2l/le/content/828830/viewContent/3627993/View)
  + Grading structure
    + 50% Labs (5)
    + 50% Projects (2)
  + Attendace options
    + Rescheduling 8/16 class
    + Asynchronous viewing process
  + Alternate meeting times
    + Complete [survey](https://docs.google.com/forms/d/e/1FAIpQLSej4jFHTdVzRRf_5uyDJx5O2IQpS4AjK9Mj3J9WMpo8H-zAcg/viewform)
  + Login on ORU CIT image and check presence of R/RStudio and Excel
  