---
title: "Introductions"
author: "D. Howell"
date: "1/22/2021"
output: 
  html_document:
    theme: flatly
---
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Welcome!

Zoom Link: https://oru.zoom.us/j/91299779087?pwd=eU5kdzNzT3NVR2dzTzhnNmYrbUM5dz09

Password: 987321

**Personal Introductions**

  * Student Introductions
    + Name, Major, Year, Origin
    
    ***
    
**Course Intro**

  * Extracting value from data
  
    ***
    [Statistics](https://towardsdatascience.com/the-5-basic-statistics-concepts-data-scientists-need-to-know-2c96740377ae)
      + Predictive modelling 
      + Analysis of data sets
      
      ***
    [Computer Science](https://www.dataquest.io/blog/what-is-a-data-engineer/) 
      + Data storage
      + ETL pipelines 
      + Implementing algorithms
      + Automation
      
      ***
  + Applications
    + [Recommendation engines for retail](https://medium.com/humansforai/recommendation-engines-e431b6b6b446)
    + [Fraud detection in banking](https://emerj.com/ai-sector-overviews/artificial-intelligence-fraud-banking/)
    + [Algorithmic trading in private equity](https://www.motherjones.com/politics/2013/02/high-frequency-trading-danger-risk-wall-street/)
    + [Image recognition in healthcare](https://medium.com/activewizards-machine-learning-company/top-7-data-science-use-cases-in-healthcare-cddfa82fd9e3)
    + [Targeted advertising](https://medium.com/@araoyeoluwasegunvhictor/the-application-of-data-science-in-targeted-advertising-e81c1f7f5b62)
    + [Natural language processing in human/computer interaction](https://towardsdatascience.com/how-amazon-alexa-works-your-guide-to-natural-language-processing-ai-7506004709d3)
    + [Professional sports management optimization](https://towardsdatascience.com/scope-of-analytics-in-sports-world-37ed09c39860)
  + [Data Science as a Career](https://www.computerscience.org/careers/data-science/)

***

**Course Structure**

  * Review units and topics on [schedule](https://github.com/drehow/CSC-201/raw/master/2021_01/meta/CSC201_Schedule_Spring2021.pdf)
    
**Course Administration**

  * Review [syllabus](https://github.com/drehow/CSC-201/raw/master/2021_01/meta/2021_Spring_Syllabus.pdf)
  * Grading structure
    + 50% Labs (5)
    + 50% Projects (2)
  * Attendace options
    + 5/15 and 5/17 class online
    + Asynchronous viewing process
    
    ***
    
**Final points**

  * Complete [survey](https://forms.gle/127RKErWiwFFLbey5)
  * Login on ORU CIT image and check presence of R/RStudio and Excel
  
  ***
  