---
title: "Grouped Summaries"
author: "D. Howell"
date: "9/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, message=F, warning=F, cache=T}
# Load Packages -----------------------------------------------------------
library(tidyverse)
library(readxl)
library(here)
library(glue)
library(janitor)

# Read in Data ------------------------------------------------------------
table_num <- 1:6

# Generic read function for this dataset
supp_read <- function(number, ...){
  read_excel(here(glue::glue("supplemental-table{number}.xlsx")), ...)
}

# 3 datasets for bikes, each of which has a corresponding City Size
small_bike <- supp_read(1, skip = 5) %>% 
  clean_names() %>% 
  mutate(city_size = "Small", 
         percentage_of_workers = as.numeric(percentage_of_workers),
         margin_of_error_2 = as.numeric(margin_of_error_2))

medium_bike <- supp_read(2, skip = 5) %>% 
  clean_names() %>% 
  mutate(city_size = "Medium")

large_bike <- supp_read(3, skip = 5) %>% 
  clean_names() %>% 
  mutate(city_size = "Large")

# Combine datasets
full_bike <- bind_rows(small_bike, medium_bike, large_bike) %>% 
  set_names(nm = c("city", "n", "percent", "moe", "city_size")) %>% 
  mutate(mode = "Bike")

 
# 3 datasets for walking, each of which has a corresponding City Size
small_walk <- supp_read(4, skip = 5) %>%
  clean_names() %>%
  mutate(city_size = "Small")

medium_walk <- supp_read(5, skip = 5) %>%
  clean_names() %>%
  mutate(city_size = "Medium")

large_walk <- supp_read(6, skip = 5) %>%
  clean_names() %>%
  mutate(city_size = "Large")

# Combine datasets
full_walk <- bind_rows(small_walk, medium_walk, large_walk) %>% 
  set_names(nm = c("city", "n", "percent", "moe", "city_size")) %>% 
  mutate(mode = "Walk")


library(stringr)
full_bike$state <- sapply(strsplit(full_bike$city, ", "), "[", 2)
full_bike <- full_bike[!is.na(full_bike$n),]

```





