---
title: "What is an IDE (RStudio)?"
author: "D. Howell"
date: "8/23/2020"
output: 
  html_document:
    theme: flatly
    toc: false
    toc_float: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***

An IDE, or Integrated Development Environment, enables programmers to consolidate the different aspects of writing a computer program.

IDEs increase programmer productivity by combining common activities of writing software into a single application: editing source code, building executables, and debugging.

Writing code is an important part of programming. We start with a blank file, write a few lines of code, and a program is born! IDEs facilitate this process with the features outlined below.

***

####1. BUILDING EXECUTABLES

***

####2. SYNTAX HIGHLIGHTING

An IDE that knows the syntax of your language can provide visual cues. Keywords, words that have special meaning like class in Java, are highlighted with different colors.

Compare these two code samples:

example 1 picture

example 2 picture

Syntax highlighting makes code easier to read by visually clarifying different elements of language syntax.

***

####3. AUTOCOMPLETE

When the IDE knows your programming language, it can anticipate what you’re going to type next!

We’ve seen statements with System.out.println() quite a bit so far. In an IDE, we might see System as an autocomplete option after only typing Sy. This saves keystrokes so the programmer can focus on logic in their code.

####4. OBJECT EXPLORER

***

####5. OTHER AUXILIARY FEATURES 

***

